const qawolf = require("qawolf");

let browser;
let context;

beforeAll(async () => {
  browser = await qawolf.launch();
  context = await browser.newContext();
  await qawolf.register(context);
});

afterAll(async () => {
  await qawolf.stopVideos();
  await browser.close();
});

test("creative2", async () => {
  const page = await context.newPage();
  await page.goto("https://www.creativesedge.co/", { waitUntil: "domcontentloaded" });
  await page.click(".elementor-widget-divider .elementor-widget-container div");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowUp");
  await page.press("body", "ArrowUp");
  await page.press("body", "ArrowUp");
  await page.press("body", "ArrowUp");
  await page.press("body", "ArrowUp");
  await page.press("body", "ArrowUp");
  await page.press("body", "ArrowUp");
  await page.press("body", "ArrowUp");
  await page.click(".wpforms-field-large");
  await page.click(".wpforms-field-large");
  await page.fill(".wpforms-field-large", "sana");
  await page.click('[placeholder="Last Name"]');
  await page.click('[placeholder="Last Name"]');
  await page.fill('[placeholder="Last Name"]', "ss");
  await page.click('[name*="-temp-"]');
  await page.click('[name*="-temp-"]');
  await page.fill('[name*="-temp-"]', "032222222111");
  await page.click('[placeholder="Email"]');
  await page.click('[placeholder="Email"]');
  await page.fill('[name*="-temp-"]', "03222222211");
  await page.click('[placeholder="Email"]');
  await page.fill('[placeholder="Email"]', "sana@gmail.com");
  await page.click('[placeholder="Company Website"]');
  await page.fill('[placeholder="Company Website"]', "versatile");
  await page.click('[placeholder=" How Did You Hear About Us?"]');
  await page.fill('[placeholder=" How Did You Hear About Us?"]', "fb");
  await page.click(".wpforms-field-medium");
  await page.click('[placeholder="Company Website"]');
  await page.fill('[placeholder="Company Website"]', "http://versatile.com");
  await page.click(".wpforms-field-medium");
  await page.fill(".wpforms-field-medium", "let me discuss");
  await page.click(".premium-button");
});