const qawolf = require("qawolf");

let browser;
let context;

beforeAll(async () => {
  browser = await qawolf.launch();
  context = await browser.newContext();
  await qawolf.register(context);
});

afterAll(async () => {
  await qawolf.stopVideos();
  await browser.close();
});

test("tuk5", async () => {
  const page = await context.newPage();
  await page.goto("https://tailwinduikit.com/", { waitUntil: "domcontentloaded" });
  await page.click(".icon-tabler-bulb");
  await page.click(".absolute");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.click(".border");
  await page.click('[data-testid="modal"] [src=" https://cdn.tuk.dev/assets/templates/reels/1. Home.png"]');
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
  await page.press("body", "ArrowDown");
});